baseURL = "https://y30n9ju1v.github.io/paper/"
languageCode = "ko-KR"
title = "y30n9ju1v's Papers"
theme = "hugo-book"

disableKinds = ["taxonomy", "term"]

[outputs]
home = ["HTML", "JSON"]

[outputFormats.JSON]
mediaType = "application/json"
baseName = "graph-data"
isPlainText = true

[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)'], ['$', '$']]
